### ISSUE TITLE
demo doesn't work: No module named 'utils'

### ISSUE THREAD

**Issue by JunMa11** [Stanford-AIMI/GREEN#3]
Hi @jbdel ,

Thanks for sharing the amazing work. 

Could you please check the new code with the demo? I got the following error:

```python
$ python         
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from green_score import GREEN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jma/Documents/multimodal/paligemma/GREEN/green_score/__init__.py", line 1, in <module>
    from .green import GREEN
  File "/home/jma/Documents/multimodal/paligemma/GREEN/green_score/green.py", line 11, in <module>
    from utils import (
ModuleNotFoundError: No module named 'utils'
>>> 



```

**Comment by jbdel** [comment]
@SophieOstmeier , this change triggers the error:

https://github.com/Stanford-AIMI/GREEN/commit/33917b590176da14d39ea2c025e47471252ed2d8#diff-c7c4410b5e4a08358f110fb5e5f4fa6ca3c2901fbd272742a99e21c78ce84269L5
can you look into  it

**Comment by SophieOstmeier** [comment]
Done, thanks!
